spring:
  application:
    name: payment-service

  config:
    import: optional:file:.env[.properties]

  r2dbc:
    url: r2dbc:mysql://localhost:3306/test
    username: root
    password: 1234

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

PSP:
  toss:
    url: https://api.tosspayments.com
    secretKey: ${TOSS_SECRET_KEY}